name: .NET 6 CI

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 6 SDK and Runtime
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        dotnet-quality: 'ga'

    - name: Display .NET info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
